/*
Created by abuchegger on 2021-01-07.
This file is part of the software provided by ARTI
Copyright (c) 2021, ARTI
All rights reserved.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef ARTI_NAV_CORE_TRANSFORMER_H
#define ARTI_NAV_CORE_TRANSFORMER_H

#include <ros/common.h>
#include <tf/transform_listener.h>
#include <tf2_ros/buffer.h>

namespace arti_nav_core
{

#if ROS_VERSION_MINIMUM(1, 14, 0) // if MELODIC (v14)
using Transformer = tf2_ros::Buffer;
#else // if KINETIC (v12)
using Transformer = tf::TransformListener;
#endif

}

#endif //ARTI_NAV_CORE_TRANSFORMER_H
